const FETCH_COMMENTS = 'FETCH_COMMENTS';
const FETCH_COMMENTS_REQUSET = 'FETCH_COMMENTS_REQUSET';
const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export {
  FETCH_COMMENTS,
  FETCH_COMMENTS_REQUSET,
  FETCH_COMMENTS_SUCCESS,
  FETCH_COMMENTS_FAILURE,
}